/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as KorporatRouteImport } from './routes/korporat'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as ArmadaIndexRouteImport } from './routes/armada.index'
import { Route as ArmadaSlugRouteImport } from './routes/armada.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const KorporatRoute = KorporatRouteImport.update({
  id: '/korporat',
  path: '/korporat',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmadaIndexRoute = ArmadaIndexRouteImport.update({
  id: '/armada/',
  path: '/armada/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmadaSlugRoute = ArmadaSlugRouteImport.update({
  id: '/armada/$slug',
  path: '/armada/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/kontak': typeof KontakRoute
  '/korporat': typeof KorporatRoute
  '/layanan': typeof LayananRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/armada/$slug': typeof ArmadaSlugRoute
  '/armada/': typeof ArmadaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/kontak': typeof KontakRoute
  '/korporat': typeof KorporatRoute
  '/layanan': typeof LayananRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/armada/$slug': typeof ArmadaSlugRoute
  '/armada': typeof ArmadaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/kontak': typeof KontakRoute
  '/korporat': typeof KorporatRoute
  '/layanan': typeof LayananRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/armada/$slug': typeof ArmadaSlugRoute
  '/armada/': typeof ArmadaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/kontak'
    | '/korporat'
    | '/layanan'
    | '/tentang-kami'
    | '/armada/$slug'
    | '/armada/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/kontak'
    | '/korporat'
    | '/layanan'
    | '/tentang-kami'
    | '/armada/$slug'
    | '/armada'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/kontak'
    | '/korporat'
    | '/layanan'
    | '/tentang-kami'
    | '/armada/$slug'
    | '/armada/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  KontakRoute: typeof KontakRoute
  KorporatRoute: typeof KorporatRoute
  LayananRoute: typeof LayananRoute
  TentangKamiRoute: typeof TentangKamiRoute
  ArmadaSlugRoute: typeof ArmadaSlugRoute
  ArmadaIndexRoute: typeof ArmadaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/korporat': {
      id: '/korporat'
      path: '/korporat'
      fullPath: '/korporat'
      preLoaderRoute: typeof KorporatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armada/': {
      id: '/armada/'
      path: '/armada'
      fullPath: '/armada/'
      preLoaderRoute: typeof ArmadaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armada/$slug': {
      id: '/armada/$slug'
      path: '/armada/$slug'
      fullPath: '/armada/$slug'
      preLoaderRoute: typeof ArmadaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  KontakRoute: KontakRoute,
  KorporatRoute: KorporatRoute,
  LayananRoute: LayananRoute,
  TentangKamiRoute: TentangKamiRoute,
  ArmadaSlugRoute: ArmadaSlugRoute,
  ArmadaIndexRoute: ArmadaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
